### ISSUE TITLE
ERC721 program in Rust

### ISSUE THREAD

**Issue by s0lness** [Hyle-org/examples#4]
Write a program to manage ERC721 tokens in Rust, which can be proved with Risc0, and deploy it on Hylé.
Here's the documentation to code [your 1st smart contract on Hylé](https://docs.hyle.eu/developers/using-the-cli/your-first-smart-contract/).

Here's an [example of the Cairo ERC20 contract](https://github.com/Hyle-org/vibe-check/tree/main/cairo-smile-token) used for the [vibe check demo](https://vibe.hyle.eu/).

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I would love to work on this isuse

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community🇷.

### How I plan on tackling this issue
I will work on this issue by following these steps:

1. Implement the ERC20 Contract in Rust
I will start by writing the ERC20 token contract in Rust, adhering to the ERC20 standard.
The contract will include all necessary functions such as transfer, approve, transferFrom, and balanceOf.
I will ensure that the contract is compatible with Risc0, allowing it to generate verifiable proofs for state transitions.
2. Integrate Risc0 for Proof Generation
I will integrate Risc0 into the Rust codebase to enable proof generation for the state transitions within the ERC20 contract.
This will involve creating proofs for operations like token transfers and ensuring these can be verified on-chain using the Hylé platform.
3. Deploy the Contract on Hylé
Following the deployment guidelines provided in the Hylé documentation, I will deploy the Rust-based ERC20 contract on the Hylé devnet.
This will include registering the contract on-chain, verifying that it functions as expected, and interacting with it through stateful transactions.
4. Documentation and Example Integration
I’ll document the entire process, including how to compile the Rust contract, generate Risc0 proofs, and deploy the contract on Hylé.
I will also update the README to include detailed instructions and examples for users to interact with the deployed contract.
5. Testing and Validation
After deployment, I’ll rigorously test the contract to ensure it operates correctly on Hylé.
I’ll verify that the Risc0 proofs are generated accurately and that state transitions are reflected on-chain as expected.

**Comment by PavitraAgarwal21** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
I am a skilled smart contract engineer with expertise in Rust, Solidity, and Cairo, with significant experience in managing ERC721 tokens and zero-knowledge technologies. My recent projects include developing complex ERC721 contracts from scratch, ensuring robust ownership and transfer mechanisms. Additionally, I am proficient with Risc0 for proving computational integrity, making me well-suited for integrating zero-knowledge proofs into Rust-based smart contracts. My experience with multi-chain ecosystems, particularly in deploying on platforms like StarkNet, positions me to effectively manage the deployment on Hylé.

### How I plan on tackling this issue
To manage ERC721 tokens in Rust with Risc0 and deploy on Hylé, I would begin by thoroughly reviewing the ERC721 standard, focusing on key functions like ownership, transfer, approval, and metadata management. I would then set up a Rust project, integrating the Risc0 crate to enable zero-knowledge proofs. Core ERC721 functions, including minting, transferring, and burning tokens, would be implemented with Rust’s efficient data structures, ensuring they are provable using Risc0. The project would include robust testing to validate functionality and the correct implementation of proofs. Finally, I would follow Hylé's deployment guidelines to compile and deploy the smart contract, ensuring it meets all platform requirements and integrates seamlessly. My background in Rust, ERC721, and zero-knowledge technologies ensures a secure and efficient solution.

**Comment by Gerson2102** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
Hello, I’m Gerson, an active member of the Dojo Coding community. I have contributed to several projects on OnlyDust, such as Madara, Kakarot, Giza, and Cairo Native. My experience with Rust comes from my participation in these projects, and I’ve worked in other personal projects woth Cairo that have allowed me to deepen my knowledge of this programming language. My goal in applying to this issue is not only to contribute my knowledge but also to expand my experience with Rust and explore new areas like integrating with Hylé. You can see more about my work on my OnlyDust profile: https://app.onlydust.com/u/Gerson2102

### How I plan on tackling this issue
First, I would focus on reviewing all the resources and documentation provided in the issue to ensure I fully understand the project’s requirements. It’s crucial to understand both the implementation of ERC721 in Rust and the Hylé platform to develop a robust smart contract. After this initial review, I would study examples of ERC721 contracts in Rust and analyze the example of the Cairo ERC20 contract mentioned. This will help me identify patterns and potential challenges.

As I progress, I plan to write code incrementally, If I encounter difficulties or have specific questions, I won’t hesitate to seek guidance in the Telegram groups or directly contact the project leads to ensure the work meets the required standards. My approach is iterative and collaborative, ensuring that each step aligns with the expectations of the team and the community.

**Comment by BernalHQ** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/hyl).

### My background and how it can be leveraged
Hi, my name is Bernal. I currently work as a software developer in Costa Rica, i have 4 years working in software development. I’m an enthusiast of Web3 technology, and I would love to contribute to this project.

### How I plan on tackling this issue
The first step is to understand the project and how it works. Once I have a good understanding of it, I’ll investigate how to manage ERC721 tokens in Rust and explore integrating Risc0 for proof generation. Then, I’ll think about an optimal solution for deploying the contract on Hylé. After that, I’ll implement the solution and run tests to validate the deployment and proof mechanism.

**Comment by wraitii** [comment]
Hello all, thanks for applying 😄 

Assigning this one to @g4titanx 
For this one, the best starting point is http://github.com/Hyle-org/collatz-conjecture since that's Rust + risc0. Consider looking at our vibe checks contracts as well.

For questions, please join [t.me/hyle_org](https://t.co/irOrk82eHL). We try to keep the docs at https://docs.hyle.eu up-to-date but things change quickly.

**Comment by suhas-sensei** [comment]
hey @wraitii im down to work on this one.
